language: python
python:
- '2.7'
addons:
  apt:
    packages:
    - doxygen
install:
- pip install .
- pip install -r test_required_packages.req
- pip install -r build_required_packages.req
script:
- "./build.sh"
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: "/docs/doxygen/html"
    github_token: "$GH_REPO_TOKEN"
    on:
      branch: master
  - provider: pypi
    user: belvedere-trading
    password:
      secure: tcabWIfQ/4j14EAENZQND6LSGJKsjMasfzKaMXeuObvHw/vOsj9MIsXRTwt/Qz15IqFonMToqBlgL04lCEJl9vBDA0tTcfBbUvmcMZhTrrNTQGkuv06/ss8L3TCEMbKrxqcrbcZz6nWnJQdY21JXk/KsmKQ47UyprSxP3GtPf11tAIalDXTPa4k3wQrdPei6ZLHrjYroGGuY40mop5V8wX61ydrhqIN6wPfTIZAeH9aWA7+bfDABHbpJGjeW1TWpJ3T3LJIoUPfjDoC/AvNW9fAR1NL0Pdv0H4jFMQEI8rltWA9To/bfUozCYFaIsUGadMyE9ShTwFJtLkjikihA+NkjrlGdYO4bbiQJyPwFSm9V6i9+qrmh+eR7Znxcqcfbgj05HKhUims8SML4edYNbpHWQxYF0P+44SR2LJOMiKxR8JDrgSIOb8qBlY5Y0baCuDrI9jcM7NtMYpysQgz7KdBBbnsoAQEga71BOmbiv8N/PYCtML3Dfb14TWpGahBrk31x6712V8CCLKa3m6jsEP/hN8mxZK3fZYlDiOJhIvVJ/LexIM2b5YlBhLtkJbITJs1wRH179yfVtnqQ/uSi18K+YVywQIAHoxQ46GME2vW1NYUg0aA3How++/jakFbFuSOQ5toqm2pSbtkl5XQZiv54lmJ8GnZOkL1/Vs2LMZg=
    distributions: sdist bdist_wheel
    on:
      tags: true
